### ISSUE TITLE
Task #4: Coloring Game

### ISSUE THREAD

**Issue by thesoupgirl** [thesoupgirl/408Proj#29]
Coloring game like Painter or Digital Cross-Stitching

Acceptance Criteria:
Given that the game page is loaded, a start button is shown that leads to the new/load page.
Given that the new/load page is loaded, options are displayed to either load a blank image, or get the template for a saved image.
Given that the new option is selected, a grid is shown that has blank tiles, and a menu bar for color selection.
Given that the load option is selected, a grid is shown that has labeled tiles, and a menu bar color selection and a color legend.
Given that a color is selected in the color bar, the user will only paint in that color.
Given that a color is selected in the color bar, the user will only be able to paint tiles of that color.
Given that the “exit” button in the grid is selected, the user is sent back to the main menu.
Given the game engine changes are made, the prior game(s) will still perform nominally.

**Comment by VinsonL19** [comment]
All tasks fulfilled and acceptance criteria satisfied
